version = 0.1

[default.deploy.parameters]
stack_name = "employee-rating"
resolve_s3 = true
s3_prefix = "employee-rating"
region = "af-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "af-south-1"
